#include "mainwindow.h"
#include <QApplication>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    w.show();

    a.setStyleSheet(
                  "QPushButton[flat=\"false\"] { "
                  "     margin: 2px; "
                  "     border: 1px solid #505050; "
                  "     border-radius: 0px; "
                  "     padding: 4px 12px 4px 12px; "
                  "     background: #f0f0f0; "
                  "     color: #000000; "
                  "     font: 75 10pt \"Calibri\";"
                  "} "
                  "QPushButton:pressed { "
                  "     margin: 2px; "
                  "     border: 2px solid #505050; "
                  "     border-radius: 0px; "
                  "     padding: 4px 12px 4px 12px; "
                  "     background-color: #f5f5f5; "
                  "     color: #ffffde; "
                  "     font: 75 10pt \"Calibri\";"
                  "} "
                  "QPushButton:hover { "
                  "     margin: 2px; "
                  "     border: 3px solid #505050; "
                  "     border-radius: 0px; "
                  "     padding: 4px 8px 4px 8px; "
                  "     background-color: #f0f0f0; "
                  "     color: #000000; "
                  "     font: 75 10pt \"Calibri\";"
                  "} "
                  " "
                  "QPushButton:disabled { "
                  "     margin: 2px; "
                  "     border: 0px solid #d4d4d4; "
                  "     border-radius: 0px; "
                  "     padding: 2px 10px 2px 10px; "
                  "	background-color: #d4d4d4; "
                  "	color: #4a4a4a; "
                  "font: 75 10pt \"Calibri\";"
                  "}"

                  "QToolButton { "
                  "     margin: 2px; "
                  "     border: 1px solid #505050; "
                  "     background: #f0f0f0; "
                  "     color: #000000; "
                  "     font: 75 10pt \"Calibri\";"
                  "} "
                  "QToolButton:pressed { "
                  "     margin: 2px; "
                  "     border: 3px solid #505050; "
                  "     background-color: #f5f5f5; "
                  "     color: #ffffde; "
                  "} "
                  "QToolButton:hover { "
                  "     margin: 2px; "
                  "     border: 2px solid #505050; "
                  "     border-radius: 0px; "
                  "     background-color: #505050; "
                  "     color: #f5f5f5; "
                  "} "
                  " "
                  "QToolButton:disabled { "
                  "     margin: 2px; "
                  "     border: 0px solid #d4d4d4; "
                  "     border-radius: 0px; "
                  "	background-color: #d4d4d4; "
                  "	color: #4a4a4a; "
                  "font: 75 10pt \"Calibri\";"
                  "}"


                  "QTableWidget { "
                  "background: #fefefe; "
                  "border: 0px solid #505050; "
                  "gridline-color:  #bdbdbd; "
                  "} "
                  " "
                  "QTableWidget::item:selected { "
                  "background: #FFE793; "
                  "color: black;  "
                  "border: 0px solid #505050; "
                  "gridline-color:  #bdbdbd; "
                  "} "

                  "QTableWidget QTableCornerButton::section { "
                  "border:0px solid #bdbdbd; "
                  "background-color:#bdbdbd; "
                  "margin: 1px; "
                  "} "
                  " "
                  "QHeaderView::section "
                  "{ "
                  "spacing: 10px; "
                  "background-color:#bdbdbd; "
                  "border:0px solid #bdbdbd; "
                  "margin: 1px; "
                  "padding: 4px; "
                  "color: #010101;  "
                  "font: 75 10pt \"Calibri\"; "
                  "}"

                  "QTabWidget::pane {  "
                  "border: 1px solid #505050; "
                  "padding: 0px; "
                  "} "
                  " "
                  "QTabWidget::tab-bar { "
                  "left: 0px;  "
                  "} "
                  " "
                  "QTabBar::tab { "
                  "background: #bdbdbd; "
                  "border: 1px solid #bdbdbd;  "
                  "padding: 4px; "
                  "} "
                  " "
                  "QTabBar::tab:selected, QTabBar::tab:hover { "
                  "background: #dadada; "
                  "} "
                  " "
                  "QTabBar::tab:selected { "
                  "border: 1px solid #505050; "
                  "background: #505050; "
                  "color: white; "
                  "border-bottom: 2px solid #505050; "
                  "padding: 2px 12px 2px 12px;  "
                  "} "
                  " "
                  "QTabBar::tab:!selected { "
                  "border: 1px solid #bdbdbd; "
                  "background: #bdbdbd; "
                  "padding: 2px 12px 2px 12px;  "
                  "border-left: 2px solid #f0f0f0; "
                  "border-right: 2px solid #f0f0f0; "
                  "border-top: 2px solid #f0f0f0; "
                  "}"
                  ""
                  "QTreeWidget { "
                  " background: #fefefe; "
                  " border: 0px solid #505050; "
                  " gridline-color:  #bdbdbd; "
                  "} "
                  "QTreeWidget::item:hover { "
                  " background: #f2f2f2; "
                  " color: black;  "
                  " border: 0px solid #505050; "
                  " gridline-color:  #bdbdbd; "
                  "} "
                  ""
                  "QTreeWidget::item:selected { "
                  "background: #FFE793; "
                  "color: black;  "
                  "border: 0px solid #505050; "
                  "gridline-color:  #bdbdbd; "
                  "} "
                  ""
                  "QComboBox {"
                  "     margin: 2px; "
                  "     border: 1px solid #505050; "
                  "     padding: 2px 10px 2px 10px; "
                  "}"
                  ""
                  "QComboBox::drop-down { "
                  "     width: 20px; "
                  "     background: #ffffff; "
                  "}"
                  "QComboBox::drop-down:hover { "
                  "     width: 20px; "
                  "     background: #505050; "
                  "}"
                  "QComboBox::down-arrow { "
                  "     image: url(:/img/cbx_down.PNG)"
                  "}"
                  "QComboBox::down-arrow:hover { "
                  "     image: url(:/img/cbx_down_white.png)"
                  "}"
                  );
    /* */

    return a.exec();
}
